package services

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/imathis/launch-vector/internal/vector/project"
)

type composeFile struct {
	Version   string                    `yaml:"version"`
	Processes map[string]composeProcess `yaml:"processes"`
}

type composeProcess struct {
	Description      string          `yaml:"description"`
	Command          string          `yaml:"command"`
	WorkingDir       string          `yaml:"working_dir"`
	Environment      []string        `yaml:"environment"`
	SuccessExitCodes []int           `yaml:"success_exit_codes,flow"`
	Shutdown         composeShutdown `yaml:"shutdown"`
}

type composeShutdown struct {
	Signal         int `yaml:"signal"`
	TimeoutSeconds int `yaml:"timeout_seconds"`
}

const composeHeader = "# Generated by vector from vector.yaml. Do not edit.\n"

// RenderCompose builds the Process Compose configuration for every app.
// Each app runs behind Portless so it gets a stable HTTPS route.
func RenderCompose(p project.Project, tld string, port int) ([]byte, error) {
	portValue := strconv.Itoa(port)
	file := composeFile{Version: "0.5", Processes: make(map[string]composeProcess, len(p.Config.Apps))}
	for _, app := range p.Config.Apps {
		host := p.Config.AppHost(app)
		command := append([]string{"portless", host}, app.Command...)
		file.Processes[app.Name] = composeProcess{
			Description: app.Title + " at " + host + "." + tld,
			Command:     shellJoin(command),
			WorkingDir:  filepath.Join(p.Root, app.Path),
			Environment: []string{
				"VECTOR_TLD=" + tld,
				"VECTOR_PORT=" + portValue,
				"PORTLESS_TLD=" + tld,
				"PORTLESS_PORT=" + portValue,
			},
			SuccessExitCodes: []int{130, 143},
			Shutdown:         composeShutdown{Signal: 2, TimeoutSeconds: 10},
		}
	}
	var buffer bytes.Buffer
	buffer.WriteString(composeHeader)
	encoder := yaml.NewEncoder(&buffer)
	encoder.SetIndent(2)
	if err := encoder.Encode(file); err != nil {
		return nil, err
	}
	if err := encoder.Close(); err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

// WriteCompose writes the generated configuration and reports whether it changed.
func WriteCompose(p project.Project, tld string, port int) (bool, error) {
	contents, err := RenderCompose(p, tld, port)
	if err != nil {
		return false, err
	}
	path := p.ComposePath()
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, contents) {
		return false, nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := writeGitignore(filepath.Dir(path)); err != nil {
		return false, err
	}
	return true, os.WriteFile(path, contents, 0o644)
}

// writeGitignore keeps machine-local state out of git even when a workspace
// .gitignore predates the state directory.
func writeGitignore(dir string) error {
	path := filepath.Join(dir, ".gitignore")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return os.WriteFile(path, []byte("*\n"), 0o644)
}

func shellJoin(args []string) string {
	quoted := make([]string, len(args))
	for i, arg := range args {
		quoted[i] = shellQuote(arg)
	}
	return strings.Join(quoted, " ")
}

func shellQuote(value string) string {
	if value != "" && strings.IndexFunc(value, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || strings.ContainsRune("-_./:=@%+,", r))
	}) == -1 {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
